import argparse
import hashlib
import json
import os
import re
import time
from pathlib import Path

from openai import OpenAI


# ============================================================
# CONFIGURATION
# ============================================================

DEFAULT_METADATA_FILE = Path(
    "output/metadata.json"
)

DEFAULT_OUTPUT_FILE = Path(
    "output/data_dictionary.json"
)

DEFAULT_CACHE_FILE = Path(
    "output/data_dictionary_cache.json"
)

OPENROUTER_MODEL = "openrouter/free"

OPENROUTER_BASE_URL = (
    "https://openrouter.ai/api/v1"
)

MAX_RETRIES = 4

RETRY_DELAY_SECONDS = 5


# ============================================================
# OPENROUTER CLIENT
# ============================================================

def create_openrouter_client():
    """
    Create and return an OpenRouter client.

    The API key is read from the OPENROUTER_API_KEY
    environment variable.
    """

    api_key = os.getenv(
        "OPENROUTER_API_KEY"
    )

    if not api_key:

        raise RuntimeError(
            "OPENROUTER_API_KEY is not configured. "
            "Please configure your OpenRouter API key "
            "as an environment variable or Codespaces secret."
        )

    try:

        client = OpenAI(
            api_key=api_key,
            base_url=OPENROUTER_BASE_URL
        )

    except Exception as error:

        raise RuntimeError(
            "Unable to initialize the OpenRouter client. "
            "Make sure your OpenRouter API credentials "
            "are configured correctly."
        ) from error

    return client


# ============================================================
# LOAD METADATA
# ============================================================

def load_metadata(metadata_file):
    """
    Load metadata JSON generated by extract_metadata.py.
    """

    metadata_file = Path(
        metadata_file
    )

    if not metadata_file.exists():

        raise FileNotFoundError(
            f"Metadata file not found: {metadata_file}"
        )

    with open(
        metadata_file,
        "r",
        encoding="utf-8"
    ) as file:

        metadata = json.load(file)

    if not isinstance(
        metadata,
        list
    ):

        raise ValueError(
            "Metadata JSON must contain a list of "
            "column metadata objects."
        )

    if len(metadata) == 0:

        raise ValueError(
            "Metadata file contains no column information."
        )

    return metadata


# ============================================================
# DATASET / METADATA FINGERPRINT
# ============================================================

def create_metadata_fingerprint(metadata):
    """
    Create a deterministic SHA-256 fingerprint from metadata.

    The fingerprint allows the profiler to determine whether
    the cached AI data dictionary belongs to the current dataset.
    """

    canonical_metadata = json.dumps(
        metadata,
        sort_keys=True,
        separators=(",", ":"),
        default=str
    )

    return hashlib.sha256(
        canonical_metadata.encode("utf-8")
    ).hexdigest()


# ============================================================
# CACHE HANDLING
# ============================================================

def load_cached_dictionary(
    output_file,
    cache_file,
    metadata
):
    """
    Load an existing AI data dictionary only if its cache
    fingerprint matches the current dataset metadata.

    Returns
    -------
    list or None
    """

    output_file = Path(
        output_file
    )

    cache_file = Path(
        cache_file
    )

    if not output_file.exists():

        return None

    if not cache_file.exists():

        return None

    try:

        with open(
            cache_file,
            "r",
            encoding="utf-8"
        ) as file:

            cache = json.load(file)

    except Exception:

        return None

    if not isinstance(
        cache,
        dict
    ):

        return None

    current_fingerprint = (
        create_metadata_fingerprint(
            metadata
        )
    )

    cached_fingerprint = cache.get(
        "metadata_fingerprint"
    )

    if cached_fingerprint != current_fingerprint:

        return None

    try:

        with open(
            output_file,
            "r",
            encoding="utf-8"
        ) as file:

            dictionary = json.load(file)

    except Exception:

        return None

    if not validate_result(
        dictionary,
        metadata
    ):

        return None

    return dictionary


def save_cache_metadata(
    cache_file,
    metadata
):
    """
    Save the fingerprint associated with the current
    AI data dictionary.
    """

    cache_file = Path(
        cache_file
    )

    cache_file.parent.mkdir(
        parents=True,
        exist_ok=True
    )

    fingerprint = (
        create_metadata_fingerprint(
            metadata
        )
    )

    cache = {
        "metadata_fingerprint": fingerprint,
        "columns": [
            item.get("column_name")
            for item in metadata
            if isinstance(item, dict)
        ]
    }

    with open(
        cache_file,
        "w",
        encoding="utf-8"
    ) as file:

        json.dump(
            cache,
            file,
            indent=2
        )


# ============================================================
# BUILD AI PROMPT
# ============================================================

def build_prompt(metadata):
    """
    Build the AI classification prompt.
    """

    prompt = f"""
You are an expert data scientist building an automated data analysis pipeline.

Analyze the following dataset column metadata and classify EVERY column.

You must distinguish between:

1. SEMANTIC TYPE
2. MEASUREMENT SCALE
3. SEMANTIC SUBTYPE

Allowed semantic types:

- categorical
- numeric
- binary
- datetime
- text
- identifier
- geographic

Allowed measurement scales:

- nominal
- ordinal
- interval
- ratio
- not_applicable

Allowed semantic subtypes:

- currency
- percentage
- none


CLASSIFICATION RULES


1. DATETIME

If a column contains dates or timestamps:

- semantic_type = "datetime"
- measurement_scale = "not_applicable"
- semantic_subtype = "none"


2. IDENTIFIER

If a column is an ID, unique identifier, respondent ID,
registration number, etc.:

- semantic_type = "identifier"
- measurement_scale = "not_applicable"
- semantic_subtype = "none"


3. TEXT

If a column contains free-form written responses:

- semantic_type = "text"
- measurement_scale = "not_applicable"
- semantic_subtype = "none"


4. GEOGRAPHIC

If a column represents location such as country,
state, district, city, latitude or longitude:

- semantic_type = "geographic"
- measurement_scale = "not_applicable"
- semantic_subtype = "none"


5. BINARY

If a variable has two meaningful categories such as Yes/No:

- semantic_type = "binary"
- measurement_scale = "nominal"
- semantic_subtype = "none"


6. CATEGORICAL NOMINAL

If a variable contains categories with no natural ordering:

- semantic_type = "categorical"
- measurement_scale = "nominal"
- semantic_subtype = "none"

Example:

Gender = Male, Female, Prefer not to say


7. CATEGORICAL ORDINAL

If categories have a meaningful natural order:

- semantic_type = "categorical"
- measurement_scale = "ordinal"
- semantic_subtype = "none"
- ordered = true
- category_order must contain categories from lowest to highest.

Example:

Education = UG, PG, PhD


8. NUMERIC RATIO

If numerical values have a meaningful zero and ratios are meaningful:

- semantic_type = "numeric"
- measurement_scale = "ratio"

Examples:

Age
Income
Number of employees
Quantity


9. CURRENCY

If a numeric variable represents money:

- semantic_type = "numeric"
- measurement_scale = "ratio"
- semantic_subtype = "currency"


10. PERCENTAGE

If a numeric variable represents a percentage:

- semantic_type = "numeric"
- measurement_scale = "ratio"
- semantic_subtype = "percentage"


11. LIKERT / RATING VARIABLES

Pay special attention to survey questions using numerical response scales.

If values represent ordered response categories such as:

1 = Strongly disagree
2 = Disagree
3 = Neutral
4 = Agree
5 = Strongly agree

classify them as:

- semantic_type = "numeric"
- measurement_scale = "ordinal"
- semantic_subtype = "none"
- ordered = true

Do NOT classify a Likert score as ratio merely because the values are numbers.

If the metadata does not provide labels for the numerical scale,
infer cautiously from:

- column name
- number of unique values
- observed range
- survey context


12. NUMBERS ARE NOT AUTOMATICALLY RATIO

Do not assign ratio measurement scale simply because Python
identifies a column as int64 or float64.

Consider the meaning of the variable.


IMPORTANT:

- Every column MUST appear exactly once.
- Do not invent columns.
- Do not invent categories.
- Do not invent measurement scales.
- Use only the allowed semantic types, measurement scales and semantic subtypes.
- "categorical" is a semantic type.
- "nominal" and "ordinal" are measurement scales.
- "numeric" is a semantic type.
- "ratio" and "interval" are measurement scales.
- "datetime", "text", "identifier", and "geographic" must use measurement_scale = "not_applicable".
- Binary variables must use nominal measurement scale.
- For ordinal categorical variables, category_order must contain categories from lowest to highest.
- For ordinal numeric variables, category_order may contain numeric response values from lowest to highest.
- For all non-ordinal variables, category_order must be [].
- Confidence must be between 0 and 1.
- When a column contains "observed_unique_values", use those values when determining its categories.
- For ordinal categorical variables, category_order must include ALL observed categories that have a meaningful order.
- Do not omit an observed category from category_order merely because it was not present in sample_values.
- For ordinal numeric variables, category_order should include all observed response values when they represent ordered response levels.


OUTPUT REQUIREMENTS

Return ONLY valid JSON.

Do not use Markdown code fences.

Do not include explanations before or after the JSON.

The response must contain one classification object for every dataset column.

Use exactly this structure:

[
  {{
    "column_name": "Age",
    "semantic_type": "numeric",
    "measurement_scale": "ratio",
    "semantic_subtype": "none",
    "confidence": 0.99,
    "ordered": false,
    "category_order": [],
    "reason": "Age has a meaningful zero and ratios are meaningful."
  }}
]

Dataset metadata:

{json.dumps(metadata, indent=2, default=str)}
"""

    return prompt


# ============================================================
# VALIDATE AI RESULT
# ============================================================

def validate_result(
    result,
    metadata
):
    """
    Validate that the AI result contains exactly the
    columns present in the metadata.
    """

    if not isinstance(
        result,
        list
    ):

        return False

    input_columns = {
        item.get("column_name")
        for item in metadata
        if isinstance(item, dict)
    }

    output_columns = {
        item.get("column_name")
        for item in result
        if isinstance(item, dict)
    }

    if input_columns != output_columns:

        return False

    if len(result) != len(input_columns):

        return False

    return True


# ============================================================
# EXTRACT JSON FROM AI RESPONSE
# ============================================================

def extract_json_from_response(response_text):
    """
    Extract a JSON object or JSON array from an AI response.

    Handles:

    1. Plain JSON
    2. Markdown JSON code fences
    3. Explanatory text before/after JSON
    4. JSON objects containing the classification list
    """

    if not response_text:

        raise ValueError(
            "OpenRouter returned an empty response."
        )

    text = str(
        response_text
    ).strip()

    if not text:

        raise ValueError(
            "OpenRouter returned an empty response."
        )

    # --------------------------------------------------------
    # Attempt 1: direct JSON parsing
    # --------------------------------------------------------

    try:

        return json.loads(
            text
        )

    except json.JSONDecodeError:

        pass

    # --------------------------------------------------------
    # Attempt 2: remove Markdown code fences
    # --------------------------------------------------------

    cleaned = re.sub(
        r"^```(?:json)?\s*",
        "",
        text,
        flags=re.IGNORECASE
    )

    cleaned = re.sub(
        r"\s*```$",
        "",
        cleaned
    ).strip()

    try:

        return json.loads(
            cleaned
        )

    except json.JSONDecodeError:

        pass

    # --------------------------------------------------------
    # Attempt 3: find JSON array
    # --------------------------------------------------------

    array_start = cleaned.find(
        "["
    )

    array_end = cleaned.rfind(
        "]"
    )

    if (
        array_start != -1
        and array_end > array_start
    ):

        candidate = cleaned[
            array_start:array_end + 1
        ]

        try:

            return json.loads(
                candidate
            )

        except json.JSONDecodeError:

            pass

    # --------------------------------------------------------
    # Attempt 4: find JSON object
    # --------------------------------------------------------

    object_start = cleaned.find(
        "{"
    )

    object_end = cleaned.rfind(
        "}"
    )

    if (
        object_start != -1
        and object_end > object_start
    ):

        candidate = cleaned[
            object_start:object_end + 1
        ]

        try:

            return json.loads(
                candidate
            )

        except json.JSONDecodeError:

            pass

    raise ValueError(
        "OpenRouter returned content that could not be "
        "parsed as valid JSON."
    )


# ============================================================
# NORMALIZE AI RESULT
# ============================================================

def normalize_ai_result(
    result
):
    """
    Normalize possible JSON wrapper structures.

    Expected final structure:

    [
        {...},
        {...}
    ]

    Some models may instead return:

    {
        "data_dictionary": [
            {...},
            {...}
        ]
    }

    or:

    {
        "columns": [
            {...},
            {...}
        ]
    }
    """

    if isinstance(
        result,
        list
    ):

        return result

    if isinstance(
        result,
        dict
    ):

        possible_keys = [
            "data_dictionary",
            "dataDictionary",
            "dictionary",
            "columns",
            "results",
            "classifications"
        ]

        for key in possible_keys:

            value = result.get(
                key
            )

            if isinstance(
                value,
                list
            ):

                return value

    return result


# ============================================================
# OPENROUTER RETRY LOGIC
# ============================================================

def generate_with_retries(
    client,
    prompt
):
    """
    Call OpenRouter with retry handling for temporary failures.
    """

    last_error = None

    for attempt in range(
        1,
        MAX_RETRIES + 1
    ):

        print(
            f"OpenRouter attempt {attempt}/{MAX_RETRIES}..."
        )

        try:

            response = client.chat.completions.create(
                model=OPENROUTER_MODEL,
                messages=[
                    {
                        "role": "system",
                        "content": (
                            "You are a data classification engine. "
                            "Follow the user's instructions exactly. "
                            "Return ONLY valid JSON. "
                            "Do not use Markdown. "
                            "Do not add explanations."
                        )
                    },
                    {
                        "role": "user",
                        "content": prompt
                    }
                ],
                temperature=0
            )

            return response

        except Exception as error:

            last_error = error

            error_text = str(
                error
            ).lower()

            retryable_terms = [
                "503",
                "unavailable",
                "overloaded",
                "high demand",
                "temporarily",
                "timeout",
                "internal server error",
                "429",
                "rate limit",
                "too many requests",
                "502",
                "504",
                "gateway",
                "connection",
                "timed out"
            ]

            is_retryable = any(
                term in error_text
                for term in retryable_terms
            )

            if (
                is_retryable
                and attempt < MAX_RETRIES
            ):

                print(
                    "OpenRouter is temporarily unavailable. "
                    f"Retrying in {RETRY_DELAY_SECONDS} seconds..."
                )

                time.sleep(
                    RETRY_DELAY_SECONDS
                )

            else:

                break

    raise RuntimeError(
        "OpenRouter failed after "
        f"{MAX_RETRIES} attempts."
    ) from last_error


# ============================================================
# SAVE RESULT
# ============================================================

def save_dictionary(
    result,
    output_file
):
    """
    Save the AI data dictionary.
    """

    output_file = Path(
        output_file
    )

    output_file.parent.mkdir(
        parents=True,
        exist_ok=True
    )

    with open(
        output_file,
        "w",
        encoding="utf-8"
    ) as file:

        json.dump(
            result,
            file,
            indent=2,
            default=str
        )

    print(
        f"AI data dictionary saved to: {output_file}"
    )

    print(
        f"Columns classified: {len(result)}"
    )


# ============================================================
# RUN AI PROFILING
# ============================================================

def profile_dataset(
    metadata_file=DEFAULT_METADATA_FILE,
    output_file=DEFAULT_OUTPUT_FILE,
    cache_file=DEFAULT_CACHE_FILE
):
    """
    Use OpenRouter to classify all dataset variables.

    The profiler first checks whether a cached dictionary
    belongs to the current dataset metadata.

    If it does, OpenRouter is skipped.

    If it does not, OpenRouter is called and a new fingerprint
    is saved.
    """

    metadata = load_metadata(
        metadata_file
    )

    print(
        "Starting AI data profiling..."
    )

    print(
        f"Columns to classify: {len(metadata)}"
    )

    # --------------------------------------------------------
    # CHECK DATASET-SPECIFIC CACHE
    # --------------------------------------------------------

    cached_dictionary = load_cached_dictionary(
        output_file=output_file,
        cache_file=cache_file,
        metadata=metadata
    )

    if cached_dictionary is not None:

        print(
            "Existing valid data dictionary found "
            "for the current dataset."
        )

        print(
            "OpenRouter call skipped."
        )

        print(
            f"AI data dictionary loaded from: {output_file}"
        )

        print(
            f"Columns classified: {len(cached_dictionary)}"
        )

        return cached_dictionary

    print(
        "No valid dataset-specific dictionary found."
    )

    print(
        "OpenRouter profiling required."
    )

    # --------------------------------------------------------
    # OPENROUTER CLIENT
    # --------------------------------------------------------

    client = create_openrouter_client()

    # --------------------------------------------------------
    # BUILD PROMPT
    # --------------------------------------------------------

    prompt = build_prompt(
        metadata
    )

    # --------------------------------------------------------
    # CALL OPENROUTER WITH RETRIES
    # --------------------------------------------------------

    response = generate_with_retries(
        client,
        prompt
    )

    # --------------------------------------------------------
    # EXTRACT RESPONSE
    # --------------------------------------------------------

    if not response:

        raise RuntimeError(
            "OpenRouter returned an empty response."
        )

    if not response.choices:

        raise RuntimeError(
            "OpenRouter returned no choices."
        )

    message = response.choices[0].message

    if message is None:

        raise RuntimeError(
            "OpenRouter returned no message."
        )

    response_text = message.content

    if response_text is None:

        raise RuntimeError(
            "OpenRouter returned an empty message."
        )

    response_text = str(
        response_text
    ).strip()

    if not response_text:

        raise RuntimeError(
            "OpenRouter returned an empty response."
        )

    # --------------------------------------------------------
    # PARSE JSON
    # --------------------------------------------------------

    try:

        result = extract_json_from_response(
            response_text
        )

        result = normalize_ai_result(
            result
        )

    except ValueError as error:

        # Print a shortened response to make future debugging
        # much easier without flooding the terminal.

        preview = response_text

        if len(preview) > 4000:

            preview = (
                preview[:4000]
                + "\n...[response truncated]"
            )

        print()
        print(
            "=" * 70
        )
        print(
            "OPENROUTER RESPONSE COULD NOT BE PARSED"
        )
        print(
            "=" * 70
        )
        print(
            preview
        )
        print(
            "=" * 70
        )
        print()

        raise ValueError(
            "OpenRouter returned invalid JSON. "
            "The data dictionary could not be parsed. "
            f"Parser error: {error}"
        ) from error

    # --------------------------------------------------------
    # VALIDATE RESULT
    # --------------------------------------------------------

    if not validate_result(
        result,
        metadata
    ):

        input_columns = {
            item.get("column_name")
            for item in metadata
            if isinstance(item, dict)
        }

        output_columns = {
            item.get("column_name")
            for item in result
            if isinstance(item, dict)
        }

        missing_columns = (
            input_columns - output_columns
        )

        extra_columns = (
            output_columns - input_columns
        )

        if missing_columns:

            raise ValueError(
                "AI profiler did not classify all columns. "
                f"Missing columns: {sorted(missing_columns)}"
            )

        if extra_columns:

            raise ValueError(
                "AI profiler returned columns that were not "
                "present in the dataset: "
                f"{sorted(extra_columns)}"
            )

        raise ValueError(
            "AI profiler returned an unexpected "
            "number of column classifications."
        )

    # --------------------------------------------------------
    # SAVE RESULT
    # --------------------------------------------------------

    save_dictionary(
        result,
        output_file
    )

    # --------------------------------------------------------
    # SAVE DATASET-SPECIFIC CACHE
    # --------------------------------------------------------

    save_cache_metadata(
        cache_file,
        metadata
    )

    print(
        f"Dataset fingerprint saved to: {cache_file}"
    )

    return result


# ============================================================
# COMMAND-LINE INTERFACE
# ============================================================

if __name__ == "__main__":

    parser = argparse.ArgumentParser(
        description=(
            "Use OpenRouter to generate an AI data dictionary "
            "from dataset metadata."
        )
    )

    parser.add_argument(
        "--metadata",
        default=str(
            DEFAULT_METADATA_FILE
        ),
        help=(
            "Path to metadata JSON. "
            "Default: output/metadata.json"
        )
    )

    parser.add_argument(
        "--output",
        default=str(
            DEFAULT_OUTPUT_FILE
        ),
        help=(
            "Path for the generated data dictionary. "
            "Default: output/data_dictionary.json"
        )
    )

    parser.add_argument(
        "--cache",
        default=str(
            DEFAULT_CACHE_FILE
        ),
        help=(
            "Path for the dataset fingerprint cache. "
            "Default: output/data_dictionary_cache.json"
        )
    )

    args = parser.parse_args()

    profile_dataset(
        metadata_file=args.metadata,
        output_file=args.output,
        cache_file=args.cache
    )