import json
import pandas as pd
from pathlib import Path


# ============================================================
# CONFIGURATION
# ============================================================

DEFAULT_OUTPUT_PATH = Path("output/metadata.json")

# Maximum number of unique values to include in metadata.
# This prevents very large categorical columns from creating
# unnecessarily large metadata files.
MAX_UNIQUE_VALUES = 100


# ============================================================
# DATA LOADING
# ============================================================

def load_data(file_path):
    """
    Load a dataset based on its file extension.

    Supported formats:
    - CSV
    - Excel (.xlsx / .xls)

    Parameters
    ----------
    file_path : str or Path
        Path to the dataset.

    Returns
    -------
    pandas.DataFrame
    """

    file_path = Path(file_path)

    if not file_path.exists():
        raise FileNotFoundError(
            f"Dataset not found: {file_path}"
        )

    if not file_path.is_file():
        raise ValueError(
            f"Input path is not a file: {file_path}"
        )

    extension = file_path.suffix.lower()

    if extension == ".csv":

        return pd.read_csv(file_path)

    elif extension in [".xlsx", ".xls"]:

        return pd.read_excel(file_path)

    else:

        raise ValueError(
            f"Unsupported file format: {extension}. "
            "Supported formats are CSV and Excel (.xlsx/.xls)."
        )


# ============================================================
# METADATA EXTRACTION
# ============================================================

def extract_metadata(file_path):
    """
    Extract metadata from any supported dataset.

    Parameters
    ----------
    file_path : str or Path
        Path to CSV or Excel dataset.

    Returns
    -------
    list
        Metadata for every column.
    """

    df = load_data(file_path)

    if df.empty:
        raise ValueError(
            "The dataset is empty. "
            "Please provide a dataset containing at least one row."
        )

    if len(df.columns) == 0:
        raise ValueError(
            "The dataset contains no columns."
        )

    metadata = []

    for column in df.columns:

        series = df[column]

        # ----------------------------------------------------
        # UNIQUE VALUES
        # ----------------------------------------------------

        unique_values = (
            series
            .dropna()
            .unique()
            .tolist()
        )

        # ----------------------------------------------------
        # LIMIT UNIQUE VALUES
        # ----------------------------------------------------

        if len(unique_values) <= MAX_UNIQUE_VALUES:

            observed_unique_values = unique_values
            unique_values_truncated = False

        else:

            observed_unique_values = (
                unique_values[:MAX_UNIQUE_VALUES]
            )

            unique_values_truncated = True

        # ----------------------------------------------------
        # COLUMN METADATA
        # ----------------------------------------------------

        column_info = {

            "column_name": column,

            "python_dtype": str(
                series.dtype
            ),

            "row_count": len(series),

            "missing_count": int(
                series.isna().sum()
            ),

            "missing_percentage": round(
                float(
                    series.isna().mean() * 100
                ),
                2
            ),

            "unique_count": int(
                series.nunique(
                    dropna=True
                )
            ),

            "sample_values": (
                series
                .dropna()
                .head(10)
                .tolist()
            ),

            "observed_unique_values": (
                observed_unique_values
            ),

            "unique_values_truncated": (
                unique_values_truncated
            )
        }

        metadata.append(
            column_info
        )

    return metadata


# ============================================================
# SAVE METADATA
# ============================================================

def save_metadata(
    metadata,
    output_path=DEFAULT_OUTPUT_PATH
):
    """
    Save extracted metadata as JSON.

    Parameters
    ----------
    metadata : list
        Metadata generated by extract_metadata().

    output_path : str or Path
        Destination JSON file.
    """

    output_path = Path(
        output_path
    )

    output_path.parent.mkdir(
        parents=True,
        exist_ok=True
    )

    with open(
        output_path,
        "w",
        encoding="utf-8"
    ) as file:

        json.dump(
            metadata,
            file,
            indent=2,
            default=str
        )

    return output_path


# ============================================================
# MAIN
# ============================================================

if __name__ == "__main__":

    import argparse

    parser = argparse.ArgumentParser(
        description=(
            "Extract metadata from a CSV or Excel dataset."
        )
    )

    parser.add_argument(
        "--input",
        required=True,
        help=(
            "Path to the input dataset "
            "(CSV, XLSX, or XLS)."
        )
    )

    parser.add_argument(
        "--output",
        default=str(DEFAULT_OUTPUT_PATH),
        help=(
            "Path for the generated metadata JSON. "
            "Default: output/metadata.json"
        )
    )

    args = parser.parse_args()

    print(
        "Starting metadata extraction..."
    )

    print(
        f"Dataset: {args.input}"
    )

    metadata = extract_metadata(
        args.input
    )

    output_path = save_metadata(
        metadata,
        args.output
    )

    print(
        f"Metadata saved to: {output_path}"
    )

    print(
        f"Columns analyzed: {len(metadata)}"
    )